In [1]:
# 引数を割り算する関数
def divide(num_1, num_2):
    div = num_1 / num_2
    return div

In [2]:
a = 24
b = 8

In [3]:
divide(24,8)

3.0

In [4]:
def divide_2(num_1 = 0, num_2 = 1):
    div = num_1 / num_2
    return div

In [5]:
divide_2(num_1 = 3.0)

3.0

In [6]:
# 可変長引数で渡された全ての値を掛け合わせる
def multiple(*number):
    mul = 1
    for num in number:
        mul *= num
    return mul

In [7]:
multiple(1,2,3,4,5)

120

In [8]:
l1 = ["a","p","p","l","e"]
l2 = ["b","a","n","a","n","a"]
print(l1.index("a"))
print(l2.index("a"))

0
1


In [9]:
r = range(4,10,2)
print(r.start,r.stop,r.step)
print(r.index(8))

4 10 2
2


In [10]:
class Customer:
    def __init__(self,customer_name,age,gym_name):
        ##インスタンス変数を初期化
        self.customer_name = customer_name
        self.age = age
        self.gym_name = gym_name
        
    def fee(self):
        if self.age < 20:
            self.fee = 3000
        elif self.age >= 65:
            self.fee = 5000
        else:
            self.fee = 10000
        return self.fee

In [11]:
c1 = Customer(customer_name = "笹岡", age = 53, gym_name = "大塚店")
c2 = Customer(customer_name = "高岡", age = 67, gym_name = "新宿店")
print(c1.customer_name)
print(c1.fee())
print(c2.customer_name)
print(c2.fee())

笹岡
10000
高岡
5000


In [12]:
def status(name,maxhp,hp,attack_point):
    # ステータスの文字列を返す
    return "%s:体力 %d/%d:攻撃力 %d" % (name,hp,maxhp,attack_point)

def attack(name,attack_point,enemy_name,enemy_hp):
        enemy_hp -= attack_point
        # システムメッセージを出力
        print("*%sの攻撃！%sに%dのダメージ！" % (name,enemy_name,attack_point))
        return enemy_hp

In [13]:
# 変数を初期化
yusha_name = "勇者"          # 名前
yusha_maxhp = 60              # 体力の最大値
yusha_hp = yusha_maxhp  # 体力の現在値
yusha_attack = 10              # 攻撃力

# 同様に初期化
slime_name = "スライム"
slime_maxhp = 15
slime_hp = slime_maxhp
slime_attack = 5

# ステータスを表示
print("------------------------------------")
print(status(yusha_name,yusha_maxhp,yusha_hp,yusha_attack))  # 勇者のステータス
print(status(slime_name,slime_maxhp,slime_hp,slime_attack))       # スライムのステータス
print("------------------------------------")

# 勇者の攻撃
slime_hp = attack(yusha_name,yusha_attack,slime_name,slime_hp)
# スライムの攻撃:
yusha_hp = attack(slime_name,slime_attack,yusha_name,yusha_hp)

# 空行を表示
print("")
print("")

# ステータスを表示
print("------------------------------------")
print(status(yusha_name,yusha_maxhp,yusha_hp,yusha_attack))  # 勇者のステータス
print(status(slime_name,slime_maxhp,slime_hp,slime_attack))       # スライムのステータス
print("------------------------------------")

------------------------------------
勇者:体力 60/60:攻撃力 10
スライム:体力 15/15:攻撃力 5
------------------------------------
*勇者の攻撃！スライムに10のダメージ！
*スライムの攻撃！勇者に5のダメージ！


------------------------------------
勇者:体力 55/60:攻撃力 10
スライム:体力 5/15:攻撃力 5
------------------------------------


In [14]:
# クラスの定義
# まずはここは読み飛ばしてかまいません
class Character:
    def __init__(self,name,maxhp,attack_point):
        self.name = name
        self.maxhp = maxhp 
        self.hp = maxhp
        self.attack_point = attack_point
        
    def status(self):
        return "%s:体力 %d/%d:攻撃力 %d"%(self.name,self.hp,self.maxhp,self.attack_point)
    
    def attack(self,enemy):
        enemy.hp -= self.attack_point
        print("*%sの攻撃！%sに%dのダメージ！"%(self.name,enemy.name,self.attack_point))

In [15]:
# インスタンスを初期化
yusha = Character("勇者",60,10)
slime = Character("スライム",15,5)

# ステータスを表示
print("------------------------------------")
print(yusha.status())  # 勇者のステータス
print(slime.status())  # スライムのステータス
print("------------------------------------")
    
# 勇者の攻撃
yusha.attack(slime)
# スライムの攻撃:
slime.attack(yusha)

# 空行を表示
print("")
print("")

# ステータスを表示
print("------------------------------------")
print(yusha.status())  # 勇者のステータス
print(slime.status())  # スライムのステータス
print("------------------------------------")

------------------------------------
勇者:体力 60/60:攻撃力 10
スライム:体力 15/15:攻撃力 5
------------------------------------
*勇者の攻撃！スライムに10のダメージ！
*スライムの攻撃！勇者に5のダメージ！


------------------------------------
勇者:体力 55/60:攻撃力 10
スライム:体力 5/15:攻撃力 5
------------------------------------


In [16]:
class Rectangle():  # 長方形のクラス
    def __init__(self,height,width):
        # 自分のインスタンス変数self.heightに__init__メソッドの引数heightを代入
        # self.heightとheightは別のものを指していることに注意
        self.height = height
        self.width = width

In [17]:
r = Rectangle(2,3)  # このときに__init__メソッドが呼ばれてr.heightに2が、r.widthに3が代入される
print("長方形の高さ",r.height)
print("長方形の幅",r.width)

長方形の高さ 2
長方形の幅 3


In [18]:
import numpy as np
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [19]:
arr[2]

array([7, 8, 9])

In [20]:
arr[1,2]

6

In [21]:
arr = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [0,1,2]]])
arr

array([[[1, 2, 3],
        [4, 5, 6]],

       [[7, 8, 9],
        [0, 1, 2]]])

In [22]:
arr.shape

(2, 2, 3)

In [23]:
arr = np.arange(12).reshape((4,3))
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [24]:
arr.T

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [25]:
import pandas as pd
from pandas import Series

/Users/naokihamaguchi/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/numexpr/cpuinfo.py:76: UserWarning: [Errno 2] No such file or directory: 'sysctl'
  stacklevel=stacklevel + 1):


In [26]:
obj = Series([3,7,10,13])

In [27]:
obj

0     3
1     7
2    10
3    13
dtype: int64

In [28]:
import numpy as np

numpy_array = np.array([3,7,10,13])

Series(numpy_array)

0     3
1     7
2    10
3    13
dtype: int64

In [29]:
obj.values

array([ 3,  7, 10, 13])

In [30]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [31]:
obj2 = Series([3,10,13,17],index = ['apple','orange','mango','peach'])
obj2

apple      3
orange    10
mango     13
peach     17
dtype: int64

In [32]:
obj2[obj2 >= 5]

orange    10
mango     13
peach     17
dtype: int64

In [33]:
obj >= 5

0    False
1     True
2     True
3     True
dtype: bool

In [34]:
data = {'Tokyo':1200,'Sapporo':800,'Osaka':1000,'Okinawa':200}

In [35]:
obj3 = Series(data)
obj3

Okinawa     200
Osaka      1000
Sapporo     800
Tokyo      1200
dtype: int64

In [36]:
prefecture = ['Tokyo','Sapporo','Osaka','Okinawa','Fukuoka']

In [37]:
obj4 = Series(data,index=prefecture)
obj4

Tokyo      1200.0
Sapporo     800.0
Osaka      1000.0
Okinawa     200.0
Fukuoka       NaN
dtype: float64

In [38]:
pd.isnull(obj4)

Tokyo      False
Sapporo    False
Osaka      False
Okinawa    False
Fukuoka     True
dtype: bool

In [39]:
pd.notnull(obj4)

Tokyo       True
Sapporo     True
Osaka       True
Okinawa     True
Fukuoka    False
dtype: bool

In [40]:
df = pd.DataFrame(
    {'名前': ['山田','鈴木','佐藤','田中','斎藤'],
     '年齢': [5,10,13,14,35],
     '性別': ['男','女','男','女','男']
    })
df

名前  年齢 性別
0  山田   5  男
1  鈴木  10  女
2  佐藤  13  男
3  田中  14  女
4  斎藤  35  男

In [41]:
# DataFrameを定義する
data = pd.DataFrame( {'国・地域': {1: 'アメリカ合衆国', 2: 'ソビエト連邦', 3: '日本（開催国）', 4: '東西統一ドイツ', 5: 'イタリア', 6: 'ハンガリー', 7: 'ポーランド', 8: 'オーストラリア', 9: 'チェコスロバキア', 10: 'イギリス'},
 '計': {1: 90, 2: 96, 3: 29, 4: 50, 5: 27, 6: 22, 7: 23, 8: 18, 9: 14, 10: 18},
 '金': {1: 36, 2: 30, 3: 16, 4: 10, 5: 10, 6: 10, 7: 7, 8: 6, 9: 5, 10: 4},
 '銀': {1: 26, 2: 31, 3: 5, 4: 22, 5: 10, 6: 7, 7: 6, 8: 2, 9: 6, 10: 12},
 '銅': {1: 28, 2: 35, 3: 8, 4: 18, 5: 7, 6: 5, 7: 10, 8: 10, 9: 3, 10: 2},
 '順': {1: 'アメリカ合衆国',
          2: 'ソビエト連邦',
          3: '日本',
          4: '東西統一ドイツ',
          5: 'イタリア',
          6: 'ハンガリー',
          7: 'ポーランド',
          8: 'オーストラリア',
          9: 'チェコスロバキア',
          10: 'イギリス'}}
)

In [42]:
data

国・地域   計   金   銀   銅         順
1    アメリカ合衆国  90  36  26  28   アメリカ合衆国
2     ソビエト連邦  96  30  31  35    ソビエト連邦
3    日本（開催国）  29  16   5   8        日本
4    東西統一ドイツ  50  10  22  18   東西統一ドイツ
5       イタリア  27  10  10   7      イタリア
6      ハンガリー  22  10   7   5     ハンガリー
7      ポーランド  23   7   6  10     ポーランド
8    オーストラリア  18   6   2  10   オーストラリア
9   チェコスロバキア  14   5   6   3  チェコスロバキア
10      イギリス  18   4  12   2      イギリス

In [43]:
data.columns

Index(['国・地域', '計', '金', '銀', '銅', '順'], dtype='object')

In [44]:
data2 = pd.DataFrame(data, columns = ['国・地域', '計', '金', '銀', '銅'])
data2

国・地域   計   金   銀   銅
1    アメリカ合衆国  90  36  26  28
2     ソビエト連邦  96  30  31  35
3    日本（開催国）  29  16   5   8
4    東西統一ドイツ  50  10  22  18
5       イタリア  27  10  10   7
6      ハンガリー  22  10   7   5
7      ポーランド  23   7   6  10
8    オーストラリア  18   6   2  10
9   チェコスロバキア  14   5   6   3
10      イギリス  18   4  12   2

In [45]:
data2.loc[3]

国・地域    日本（開催国）
計            29
金            16
銀             5
銅             8
Name: 3, dtype: object

In [46]:
data2.head()

国・地域   計   金   銀   銅
1  アメリカ合衆国  90  36  26  28
2   ソビエト連邦  96  30  31  35
3  日本（開催国）  29  16   5   8
4  東西統一ドイツ  50  10  22  18
5     イタリア  27  10  10   7

In [47]:
data2.head(3)

国・地域   計   金   銀   銅
1  アメリカ合衆国  90  36  26  28
2   ソビエト連邦  96  30  31  35
3  日本（開催国）  29  16   5   8

In [48]:
data.tail()

国・地域   計   金   銀   銅         順
6      ハンガリー  22  10   7   5     ハンガリー
7      ポーランド  23   7   6  10     ポーランド
8    オーストラリア  18   6   2  10   オーストラリア
9   チェコスロバキア  14   5   6   3  チェコスロバキア
10      イギリス  18   4  12   2      イギリス

In [49]:
data.columns

Index(['国・地域', '計', '金', '銀', '銅', '順'], dtype='object')

In [50]:
data3 = pd.DataFrame(data, columns = ['国・地域', '計', '金', '銀', '銅', '選手数'])
data3

国・地域   計   金   銀   銅  選手数
1    アメリカ合衆国  90  36  26  28  NaN
2     ソビエト連邦  96  30  31  35  NaN
3    日本（開催国）  29  16   5   8  NaN
4    東西統一ドイツ  50  10  22  18  NaN
5       イタリア  27  10  10   7  NaN
6      ハンガリー  22  10   7   5  NaN
7      ポーランド  23   7   6  10  NaN
8    オーストラリア  18   6   2  10  NaN
9   チェコスロバキア  14   5   6   3  NaN
10      イギリス  18   4  12   2  NaN

In [51]:
import numpy as np
data3['選手数'] = np.arange(10)

In [52]:
data3

国・地域   計   金   銀   銅  選手数
1    アメリカ合衆国  90  36  26  28    0
2     ソビエト連邦  96  30  31  35    1
3    日本（開催国）  29  16   5   8    2
4    東西統一ドイツ  50  10  22  18    3
5       イタリア  27  10  10   7    4
6      ハンガリー  22  10   7   5    5
7      ポーランド  23   7   6  10    6
8    オーストラリア  18   6   2  10    7
9   チェコスロバキア  14   5   6   3    8
10      イギリス  18   4  12   2    9

In [53]:
from pandas import Series
p = Series(['200','300'],index = [2,5])
data3['選手数'] = p
data3

国・地域   計   金   銀   銅  選手数
1    アメリカ合衆国  90  36  26  28  NaN
2     ソビエト連邦  96  30  31  35  200
3    日本（開催国）  29  16   5   8  NaN
4    東西統一ドイツ  50  10  22  18  NaN
5       イタリア  27  10  10   7  300
6      ハンガリー  22  10   7   5  NaN
7      ポーランド  23   7   6  10  NaN
8    オーストラリア  18   6   2  10  NaN
9   チェコスロバキア  14   5   6   3  NaN
10      イギリス  18   4  12   2  NaN

In [54]:
del data3['選手数']

In [55]:
data3

国・地域   計   金   銀   銅
1    アメリカ合衆国  90  36  26  28
2     ソビエト連邦  96  30  31  35
3    日本（開催国）  29  16   5   8
4    東西統一ドイツ  50  10  22  18
5       イタリア  27  10  10   7
6      ハンガリー  22  10   7   5
7      ポーランド  23   7   6  10
8    オーストラリア  18   6   2  10
9   チェコスロバキア  14   5   6   3
10      イギリス  18   4  12   2

In [56]:
data3.drop(9, axis = 0)

国・地域   計   金   銀   銅
1   アメリカ合衆国  90  36  26  28
2    ソビエト連邦  96  30  31  35
3   日本（開催国）  29  16   5   8
4   東西統一ドイツ  50  10  22  18
5      イタリア  27  10  10   7
6     ハンガリー  22  10   7   5
7     ポーランド  23   7   6  10
8   オーストラリア  18   6   2  10
10     イギリス  18   4  12   2

In [57]:
data3.drop('金',axis = 1)

国・地域   計   銀   銅
1    アメリカ合衆国  90  26  28
2     ソビエト連邦  96  31  35
3    日本（開催国）  29   5   8
4    東西統一ドイツ  50  22  18
5       イタリア  27  10   7
6      ハンガリー  22   7   5
7      ポーランド  23   6  10
8    オーストラリア  18   2  10
9   チェコスロバキア  14   6   3
10      イギリス  18  12   2

In [58]:
data3.ix[1:6,:]

/Users/naokihamaguchi/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


国・地域   計   金   銀   銅
1  アメリカ合衆国  90  36  26  28
2   ソビエト連邦  96  30  31  35
3  日本（開催国）  29  16   5   8
4  東西統一ドイツ  50  10  22  18
5     イタリア  27  10  10   7
6    ハンガリー  22  10   7   5

In [59]:
data3.ix[:5, 0:2]

国・地域   計
1  アメリカ合衆国  90
2   ソビエト連邦  96
3  日本（開催国）  29
4  東西統一ドイツ  50
5     イタリア  27

In [65]:
data3.ix[0:2,:4]

国・地域   計   金   銀
1  アメリカ合衆国  90  36  26
2   ソビエト連邦  96  30  31